name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test -- --watch=false --browsers=ChromeHeadless
      - run: npx ng deploy --base-href=/pokemon-roulette-enhanced/ --name="github-actions[bot]" --email="github-actions[bot]@users.noreply.github.com"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
