export type RegularItemName =
  | 'potion'
  | 'rare-candy'
  | 'running-shoes'
  | 'super-potion'
  | 'x-attack'
  | 'exp-share'
  | 'hyper-potion'
  | 'escape-rope'
  | 'honey'
  | 'repel'
  | 'poke-radar'
  | 'max-repel'
  | 'link-cable'
  | 'revive';
